#!/bin/bash
# run_baseline_cgc.sh - Baseline comparison script for CGC binary

BINARY="binaries/cgc_cadet_00001_instrumented"
OUTPUT_DIR="data/outputs_baseline_cgc"
INPUT_DIR="data/inputs_cgc_cadet_00001"
DURATION="30m"

echo "================================================================"
echo "BASELINE AFL++ CAMPAIGN (30 Minutes)"
echo "Binary: $BINARY"
echo "Output: $OUTPUT_DIR"
echo "Input:  $INPUT_DIR"
echo "================================================================"

# Cleanup Output (Do NOT clean input, as it is shared/generated by NeuroFuzz)
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Ensure inputs exist (NeuroFuzz usually generates them, but if running standalone...)
if [ ! -d "$INPUT_DIR" ] || [ -z "$(ls -A $INPUT_DIR)" ]; then
    echo "Creating minimal input directory (NeuroFuzz usually handles this)..."
    mkdir -p "$INPUT_DIR"
    echo "AAAA" > "$INPUT_DIR/seed_basic.txt"
fi

# Start AFL++ in background
echo "[*] Starting AFL++..."
# -V 1800 seconds = 30 minutes
afl-fuzz -i "$INPUT_DIR" -o "$OUTPUT_DIR" -V 1800 -m none -- "./$BINARY" > "$OUTPUT_DIR/afl.log" 2>&1 &
AFL_PID=$!

echo "[*] AFL++ running (PID $AFL_PID). Waiting for $DURATION..."
wait $AFL_PID

echo "[*] Baseline campaign complete."
